# Generated by Django 5.0.1 on 2024-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_reservation_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
    ]
